### ISSUE TITLE
Read configuration file

### ISSUE THREAD

**Issue by rmrhz** [overtrue/phplint#1]
It would be better if the project can provide an option where it will a configuration file to read in linting specific folders or files instead of explicitly define them over the cli.

**Comment by overtrue** [comment]
@rmrhz Thanks, I will do it next version. :smile:

**Comment by rmrhz** [comment]
Oh we posted it nearly at the same time ^_^

**Comment by overtrue** [comment]
@rmrhz 😆

**Comment by rmrhz** [comment]
Looking forward in the next iteration 谢谢你 :D

**Comment by overtrue** [comment]
@rmrhz ❤️

**Comment by overtrue** [comment]
@rmrhz do you perfer to using yaml or php to config the project ?

**Comment by rmrhz** [comment]
@overtrue hmmm, considering interoperability we could go with both ways. lets try yaml for now as it would be easier to parse through and through.

**Comment by overtrue** [comment]
`.phplint.yaml`:

```yaml
path: ./app
jobs: 5
extensions:
  - php
exclude:
  - vendor
```
---
`.phplint`
```php
return [
    'path' => './app',
    'jobs' => 5,
    'extensions' => ['php'],
    'exclude' => ['vendor'],
];
```

**Comment by rmrhz** [comment]
@overtrue looks great :+1:

**Comment by overtrue** [comment]
@rmrhz OK, I will both support them.

**Comment by abrahamgreyson** [comment]
vot for yaml
