### ISSUE TITLE
PHAR releases gone since v.3.0.1

### ISSUE THREAD

**Issue by nifr** [overtrue/phplint#103]
Hi @overtrue - first of all thank you for you awesome work on phplint.

Currently the PHAR archives aren't added to the releases any more.
Also there are no `.asc` files. 

I'd really love to install `phplint` in our projects with `phive`.

Can I help somehow to fix this?

**Comment by overtrue** [comment]
@nifr I'm very sorry that this issue was not dealt with immediately due to time issues. Have you considered using https://github.com/vimeo/psalm ? I find that it is already much more powerful than this package.
