### ISSUE TITLE
Application version doesn't match release version

### ISSUE THREAD

**Issue by jakubboucek** [overtrue/phplint#104]
https://github.com/overtrue/phplint/blob/a8cef929e230e0bef5685760e1a9674a12a587ca/src/Console/Application.php#L24

Current release version: 3.0.3
Application announces: 2.0.2

**Comment by llaville** [comment]
With latest PR 111, I think issue is now solved and this report should be closed.
Here is the result after installing the package with PHP 7.4

![phplint_php74](https://user-images.githubusercontent.com/364342/143537398-08a63181-7647-4768-8c70-11c5c08b3054.png)

BTW, I've noticed a little error (still require v2.0) on https://github.com/overtrue/phplint/blob/7.4/Dockerfile#L4 for Docker version PHP 7 compatible version. I'll submit a PR to fix it !
