### ISSUE TITLE
Composer dependencies require a PHP version ">= 8.0.2".

### ISSUE THREAD

**Issue by vebe** [overtrue/phplint#113]
Since your last update I get this error:
```
PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.2". You are running 7.4.26. in /root/.composer/vendor/composer/platform_check.php on line 24
```

I'm using your 7.4 version

**Comment by overtrue** [comment]
Plz check the installed version:

```bash
$ composer info overtrue/phplint
```

**Comment by BartVanGestel** [comment]
Can confirm since +/- 14 hours ago my build are failing via the Github actions.
```
PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.2". You are running 7.4.26.

**Comment by overtrue** [comment]
@BartVanGestel `overtrue/phplint@8.0` or `overtrue/phplint@7.4` ？

**Comment by BartVanGestel** [comment]
Also `overtrue/phplint@7.4` same version as @vebe

**Comment by vebe** [comment]
@overtrue It seems to work when running it locally but fails in Github actions.
from `composer info overtrue/phplint`:
```
versions : * 2.4.1
```

**Comment by overtrue** [comment]
@vebe @BartVanGestel I am sorry, I have fixed it, plz try again.

https://github.com/overtrue/phplint-test/runs/4369761432?check_suite_focus=true

**Comment by vebe** [comment]
@overtrue Works now. Thank you!

**Comment by overtrue** [comment]
@vebe Thank you for your feedback.

**Comment by BartVanGestel** [comment]
@overtrue Yes it works again, thanks!

**Comment by MisterZ01** [comment]
fisrt, run `composer update` , then,` run composer install`
