### ISSUE TITLE
Run failures in Github Actions

### ISSUE THREAD

**Issue by purdy** [overtrue/phplint#114]
We've started seeing Action failures with phplint. We first noticed errors on Monday complaining about a PHP 8 requirement (we're using overtrue/phplint@7.4). That error went away and is now replaced by another error that indicates the path configuration we have setup in the workflow isn't respected:

```
Run overtrue/phplint@7.4
  with:
    path: sites/all/modules/custom
/usr/bin/docker run --name b621dc541541e9946aca4496eae9bd2c30f_d3dae0 --label 905b62 --workdir /github/workspace --rm -e INPUT_PATH -e INPUT_OPTIONS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/fsrd7/fsrd7":"/github/workspace" 905b62:1dc541541e9946aca4496eae9bd2c30f
phplint 3.0 by overtrue and contributors.

No config file loaded.

.......................................   40 / 10529 (0%)
```

There are only 600 or so files in `sites/all/modules/custom` folder, so to me, it appears that it's not respecting the path provided in the workflow file.

Another case has it running out of memory right around 14000 files (and again, only 600 or so files in the specified folder):

```
........................................ 14360 / 14414 (99%)
........................................ 14400 / 14414 (99%)
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 2097152 bytes) in /root/.composer/vendor/overtrue/phplint/src/Cache.php on line 65
...............
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 2097152 bytes) in /root/.composer/vendor/overtrue/phplint/src/Cache.php on line 65
```

**Comment by overtrue** [comment]
Thanks your feedback, I will fix this.

**Comment by jasonmccreary** [comment]
@overtrue, any progress here? Glad to help as we're suddenly experiencing issues with our builds without changing anything. Seems the `exclude` lists are no longer being honored.

**Comment by overtrue** [comment]
@jasonmccreary I'm very sorry for trying to fix it, but other work has been disrupting my pace lately, so if you guys can help fix it of course it would be great. Anyway, I will fix it in 48 hours at the latest.

**Comment by overtrue** [comment]
@jasonmccreary @purdy Please take a try.

**Comment by overtrue** [comment]
I made a demo, it works: https://github.com/overtrue/phplint-test/runs/4486363898?check_suite_focus=true#step:5:7

**Comment by overtrue** [comment]
It seems like it has been fixed: https://github.com/overtrue/phplint-test/runs/4486443601?check_suite_focus=true

**Comment by jasonmccreary** [comment]
@overtrue, no worries. I know how it is with these things. 🤗 

Thanks for fixing!

**Comment by overtrue** [comment]
@jasonmccreary 🍻

**Comment by purdy** [comment]
Sorry about the late response, but our errors have also gone away with this update. Thanks!

**Comment by overtrue** [comment]
@purdy ❤️
