### ISSUE TITLE
Support for PHP 8.1

### ISSUE THREAD

**Issue by txigreman** [overtrue/phplint#120]
I would love to have support for php 8.1.

**Comment by overtrue** [comment]
@txigreman I have created a branch `8.1` and new release ` 5.0.0` which require PHP >= 8.1, please take a try. sorry for the late response.

**Comment by txigreman** [comment]
Thanks a lot! When are you planning to push it to Docker hub?

**Comment by txigreman** [comment]
I've seen there is a problem in the Dockerfile, and sent you a pull request fixing it. I hope it helps.

**Comment by overtrue** [comment]
> Thanks a lot! When are you planning to push it to Docker hub?

https://hub.docker.com/r/overtrue/phplint/tags
