### ISSUE TITLE
Readd support for symfony/console:^5

### ISSUE THREAD

**Issue by evs-xsarus** [overtrue/phplint#125]
Trying to install this package on Magento 2.4.4 with PHP 8.1 and it fails because Magento has symfony/console locked to v5. Could this support be readded.

**Comment by llaville** [comment]
Fixe was applied in context of PR #143 for issue #142, but it should also fix this bug. @evs-xsarus please confirm, and feel free to close this report

**Comment by evs-xsarus** [comment]
Seems to be working.
