### ISSUE TITLE
Make releases to packagist with new option --no-files-exit-codes

### ISSUE THREAD

**Issue by vkryklyvenko** [overtrue/phplint#129]
I created three pull requests to add new option --no-files-exit-codes
Could you make new releases because I can't use new changes by composer

**Comment by overtrue** [comment]
@vkryklyvenko 
8.1 https://github.com/overtrue/phplint/releases/tag/5.2.0
8.0 https://github.com/overtrue/phplint/releases/tag/4.2.0

**Comment by vkryklyvenko** [comment]
> @vkryklyvenko 8.1 https://github.com/overtrue/phplint/releases/tag/5.2.0 8.0 https://github.com/overtrue/phplint/releases/tag/4.2.0

Could you do it for 7.4 too please
