### ISSUE TITLE
测试出错没有返回具体行数   只是一个Unknow

### ISSUE THREAD

**Issue by liuyao729** [overtrue/phplint#13]
php版本是 5.6.9
phplint版本是 0.0.3

**Comment by overtrue** [comment]
首先你的错误也许本来就是不可标记的，比如你的错误在生成的代码里，比如使用 create_function 或者 使用 eval 产生的代码里的错，肯定是无法确定行的。

![image](https://cloud.githubusercontent.com/assets/1472352/17728307/471c0b90-6491-11e6-8ba2-96ae717cf0f5.png)

**Comment by liuyao729** [comment]
![image](https://cloud.githubusercontent.com/assets/1097825/17728604/a5cebad8-6492-11e6-96a1-ab64d571862b.png)
![image](https://cloud.githubusercontent.com/assets/1097825/17728837/c0e4e7a6-6493-11e6-9e65-48ac731a2d09.png)

**Comment by overtrue** [comment]
@liuyao729 你用 PHP 的语法检查工具看看：

```shell
$ php -l FILENAME
```

**Comment by liuyao729** [comment]
有错误提示
![image](https://cloud.githubusercontent.com/assets/1097825/17729590/7a649b24-6497-11e6-99b4-15610c19e852.png)

**Comment by overtrue** [comment]
@liuyao729 OK,我来看看问题在哪

**Comment by overtrue** [comment]
@liuyao729 修复了，在于报错信息不一样，有的报错是 

```
PHP Parse error: xxxx
```

有的是：

```php
Parse error: xxxx
```

已经在 0.0.4 版本修复。

**Comment by liuyao729** [comment]
赞

**Comment by liuyao729** [comment]
另外我还发现如果display_errors=Off 的情况下
会有Errors parsing <file>   出现这个错误的时候可以提示打开display_errors

**Comment by overtrue** [comment]
@liuyao729 求截图

**Comment by liuyao729** [comment]
由于你对getOutput  做过处理  所以过滤掉了错误就是Unknow
我直接把getOutput打出来了
![image](https://cloud.githubusercontent.com/assets/1097825/17766410/8b75318c-655d-11e6-8269-b76a153e8697.png)

**Comment by overtrue** [comment]
@liuyao729 搞定了。
