### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by tarlepp** [overtrue/phplint#130]

**Comment by llaville** [comment]
Planned to be included in a full documentation for upcoming version 9.0

**Comment by llaville** [comment]
Configuration documentation is [available online](https://github.com/overtrue/phplint/blob/main/docs/configuration.md) for upcoming release 9.0 

I've wrote all documentation (except contributing guide) and README page were also updated on [`main` branch](https://github.com/overtrue/phplint/tree/main)  

Reviewers are welcome ! /cc @overtrue

**Comment by overtrue** [comment]
> Configuration documentation is [available online](https://github.com/overtrue/phplint/blob/main/docs/configuration.md) for upcoming release 9.0 
> 
> 
> 
> I've wrote all documentation (except contributing guide) and README page were also updated on [`main` branch](https://github.com/overtrue/phplint/tree/main)  
> 
> 
> 
> Reviewers are welcome ! /cc @overtrue 
> 
> 

Great job, Thank you for your contribution.

**Comment by llaville** [comment]
@tarlepp I've renamed your initial report because I want to track all Documentation tasks with this report !

**Comment by llaville** [comment]
@overtrue I've push GitHub ISSUE TEMPLATEs with commit df44f2b4cd478493dd628af7e22bc8652a01bda0.

If you're agree with these contents, could you enable it (https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

**Comment by llaville** [comment]
@overtrue I've introduced the CONTRIBUTING guide with commit fd3fcaa8334ff13c7cc731f8ff080e96ebbc9718.
Review and agreement will be welcome !

**Comment by llaville** [comment]
@overtrue I've introduced the quick UPGRADING guide with commit e1705870724fde91b2d3ce9749d2e8e177957415

**Comment by overtrue** [comment]
> @overtrue I've introduced the quick UPGRADING guide with commit e1705870724fde91b2d3ce9749d2e8e177957415

👍

**Comment by llaville** [comment]
@overtrue You didn't reply about GitHub ISSUE TEMPLATEs activation (https://github.com/overtrue/phplint/issues/130#issuecomment-1398261198) ? What's your status about this purpose ?

**Comment by overtrue** [comment]
> @overtrue You didn't reply about GitHub ISSUE TEMPLATEs activation (https://github.com/overtrue/phplint/issues/130#issuecomment-1398261198) ? What's your status about this purpose ?

You did a great job, go ahead and do what you want, thank you!

**Comment by llaville** [comment]
> You did a great job, go ahead and do what you want, thank you!

Thanks. 
BTW I've found an answer to my question. ISSUE TEMPLATEs are only enabled for the repository default branch. 

As default branch is still `8.1`, we cannot see it yet ! 
We will have to wait release of final version 9.0, before to switch default branch to `main` and see ISSUE TEMPLATEs active !

**Comment by llaville** [comment]
Documentation is now completed. Look at https://github.com/overtrue/phplint/tree/main/docs, especially the architecture guide if you want to learn more about changes since previous versions

**Comment by llaville** [comment]
@overtrue As I'll release major version 9.0.0 today, could you switch default branch to `main` (that will activate the GitHub issues templates)

**Comment by overtrue** [comment]
@llaville it is done.

**Comment by llaville** [comment]
Closing this report as documentation ready for 9.0.0
