### ISSUE TITLE
Command `phplint --version` is outputting wrong version

### ISSUE THREAD

**Issue by tarlepp** [overtrue/phplint#131]
I have this in my `composer.json` file
```
"overtrue/phplint": "5.2.0",
```

and when I run `phplint --version` command I get:
```bash
phplint 5.0
```

**Comment by overtrue** [comment]
Ignore it.

**Comment by tarlepp** [comment]
> Ignore it.

Sure I can ignore it, but that is still a bug in this tool and that is why created this issue.

**Comment by overtrue** [comment]
@tarlepp Yes, I will fix it. Thanks.
