### ISSUE TITLE
Incorrect error message in `bin/phplint` file

### ISSUE THREAD

**Issue by tarlepp** [overtrue/phplint#132]
If you look - https://github.com/overtrue/phplint/blob/8.1/bin/phplint#L4-L6 - it's telling that you need at least use PHP 5.5.9 version and it looks like that is not anymore true - https://github.com/overtrue/phplint/blob/8.1/README.md#required - that part is telling that minimum PHP version is 8.1

**Comment by overtrue** [comment]
Hello, @tarlepp I won't have much time to maintain this project, Do you interested in maintaining this repo?  I can transfer it to you, Thanks.

**Comment by llaville** [comment]
Fixed now for branch 8.1 but also 8.0

**Comment by llaville** [comment]
This issue was fixed with new releases published 2 month ago. @tarlepp if you think this bug is not fixed please open a new report !
