### ISSUE TITLE
Scheduling new releases v3/v4/v5

### ISSUE THREAD

**Issue by llaville** [overtrue/phplint#148]
@overtrue I think we are almost ready for new releases 
- v3 on branch 7.4 
- v4 on branch 8.0
- v5 on branch 8.1

As we have introduced a little new feature (overriding `memory_limit` by config file;  see #137), I suggest to bump Application versions to
3.2, 4.3 and 5.3 / Are you agree ?

We are still waiting feedback from issues #125 and #132 

Issue(s) fixed : 

- #139 
- #142

**Comment by overtrue** [comment]
@llaville I agree, I think we can release the version now, if they don't reply for a long time, we don't have to wait, when the new version is released if they try there are still new problems we can release the patch to fix it again, thank you for your work. :+1:

**Comment by llaville** [comment]
@overtrue OK, so I'll bump new versions 3.2, 4.3 and 5.3, and let you publish officially the releases

**Comment by llaville** [comment]
Sorry, no more free time until tomorrow

**Comment by overtrue** [comment]
> Sorry, no more free time until tomorrow

OK,Thanks

**Comment by overtrue** [comment]
https://github.com/overtrue/phplint/releases/tag/5.3.0
https://github.com/overtrue/phplint/releases/tag/4.3.0
https://github.com/overtrue/phplint/releases/tag/3.2.0

@llaville Done.

**Comment by overtrue** [comment]
Thanks for your contributions.

Laurent Laville ***@***.***>于2022年7月11日 周一23:39写道：
