### ISSUE TITLE
Add support for upcoming version PHP 8.2

### ISSUE THREAD

**Issue by llaville** [overtrue/phplint#150]
We need to add a new major version 6.0 that will support upcoming PHP 8.2 scheduled for November, 24 2022.

**Comment by llaville** [comment]
Will do, this week :)

**Comment by llaville** [comment]
My roadmap / Will do : 

- [ ] initialize new branch `6.0` that will support future PHP 8.2 version.
- [ ] tag new application version to `6.0-dev` until PHP 8.2 reach stable status (scheduled for November 24, 2022, see [dedicated page](https://wiki.php.net/todo/php82) on PHP Wiki)
- [ ] upgrade README page corresponding to new PHP version
- [ ] add basic test to verify that application is able to lint a pure PHP 8.2 syntax

**Comment by llaville** [comment]
Branch `8.2` was initialized by following commands : 

```
export PHP_CS_FIXER_IGNORE_ENV=1
git push origin 8.2
```

**Comment by llaville** [comment]
Commit a57c612731d5cd000df74b4d8770ec3ad304943b, bump new Application version to **6.0-dev** and fix composer php requirements.

**Comment by llaville** [comment]
README page was updated with commit 565340ee5d32df9042de3f12c960415cb24a99d3

**Comment by llaville** [comment]
Updated source code with commit 1b8c2281add39cf441aaa714ff7486239249704f and 7fe6938672abf84a39b42f886f0c256dd6e5ff61

**Comment by llaville** [comment]
Now [Docker version 8.2](https://hub.docker.com/r/overtrue/phplint/tags?page=1&name=8.2) is available, we can upgrade CI workflow with commit f9aeb16f4dcffcc50e0ba3b8dbc016b30f985412

**Comment by llaville** [comment]
Before to update CI and check a pure PHP 8.2 syntax file like this one 

```php
<?php
readonly class MyValueObject {
    public string $myValue;
}
```

we need to publish a 6.0-dev version to Packagist. @overtrue are your agree with all steps ?

**Comment by overtrue** [comment]
It is good,just do it.

**Comment by llaville** [comment]
@overtrue I've prepared a draft for release 6.0.0 (https://github.com/overtrue/phplint/releases/tag/untagged-410d5d58f3c17a7afd7b) 
If you're agree, you can confirm and change its status !

**Comment by overtrue** [comment]
> @overtrue I've prepared a draft for release 6.0.0 (https://github.com/overtrue/phplint/releases/tag/untagged-410d5d58f3c17a7afd7b) If you're agree, you can confirm and change its status !


Hi, @llaville I've published it. Thanks.

**Comment by llaville** [comment]
As Release 6.0.0 should be considered as beta rather than a stable version, I've used recent feature to [Explicitly Set the Latest Release](https://github.blog/changelog/2022-10-21-explicitly-set-the-latest-release/), and update accordingly the 5.3.0 version.

/cc @overtrue FYI

**Comment by llaville** [comment]
Branch `8.2` is up-to-date to support PHP 8.2.0 stable version. Release 6.0.1 will come soon after resolving issue #164 affected all branches (versions)
