### ISSUE TITLE
Docker version build failed when git tag is pushed

### ISSUE THREAD

**Issue by llaville** [overtrue/phplint#152]
Read https://docs.github.com/en/actions/learn-github-actions/environment-variables to learn more about **GITHUB_REF** env variable used by Docker workflow (see statement `run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"`).

Suggestion: prevent Docker workflow running if **GITHUB_REF_TYPE** is not `branch`

**Comment by llaville** [comment]
More simple : `on push branches [ ]`

**Comment by llaville** [comment]
Extract banch name by using deprecated [set-output](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) command generate a warning.

**Comment by llaville** [comment]
Re-building Docker image each time we push changes on branch is now easy and did not generate any warning (due to deprecated command).
`docker.yml` workflow is only triggered when pushing branch and not when tag is applied. 
So I think this issue is now really fixed. @overtrue are you agree ?

**Comment by overtrue** [comment]
> Re-building Docker image each time we push changes on branch is now easy and did not generate any warning (due to deprecated command).
> 
> `docker.yml` workflow is only triggered when pushing branch and not when tag is applied. 
> 
> So I think this issue is now really fixed. @overtrue are you agree ?  

OK

**Comment by llaville** [comment]
Before to close this issue, I will apply same fix tomorrow on other branches. 
I'm also preparing a code change I'll propose to you @overtrue for review by a new PR

**Comment by overtrue** [comment]
Thanks.

**Comment by llaville** [comment]
Available in latest releases 3.3.1, 4.4.0, 5.4.1 and 6.0.3
