### ISSUE TITLE
Lint command does not run if config file is missing

### ISSUE THREAD

**Issue by purdy** [overtrue/phplint#168]
New version was just released and it breaks existing actions when the .phplint.yml file is missing:

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/114963/209179417-cd684955-7d8b-424f-a0d5-15ab9e96ebed.png">

**Comment by llaville** [comment]
Fix is on way !

**Comment by llaville** [comment]
Fix was applied to all branches (7.4, 8.0, 8.1 and 8.2) and new releases for v3, v4, v5 and v6 are now available !
