### ISSUE TITLE
Please support an option that can check only the files you changed

### ISSUE THREAD

**Issue by paladox** [overtrue/phplint#17]
Hi please support an options that checks only the files you changed please?

**Comment by overtrue** [comment]
@paladox Every process will cache the result by filename. if the file not changed, the next process will read the result from cache. 😄

**Comment by paladox** [comment]
Oh thankyou :)

**Comment by overtrue** [comment]
```shell
#files

phplint ./a.php ./b.php ./c.php

#dirs

phplint path/to/foo path/to/bar 

#files + dir

phplint path/to/file.php  path/to/dir  path/to/foo.php 
```
😄
