### ISSUE TITLE
[9.0.0] PHAR version not available

### ISSUE THREAD

**Issue by llaville** [overtrue/phplint#175]
## Summary
Release workflow did not build the PHAR version of PHPLint 9.0.0 
(https://github.com/overtrue/phplint/actions/runs/4162210510/jobs/7201105513)

## Expected behaviour
PHAR built

## Actual behaviour
PHAR version not available

**Comment by llaville** [comment]
@overtrue I've a permission denied https://github.com/overtrue/phplint/actions/runs/4164613643/jobs/7206478202#step:7:21 when create a new release (with release workflows). 
Could you check-in and give me your feedback please ?

**Comment by overtrue** [comment]
I just tried to re-run it and also reported the same error, the logs are as follows.

https://github.com/overtrue/phplint/actions/runs/4164613643/jobs/7206478202#step:7:21

Is it because the path to the .phar file is not the right value?

Build:
>  Building the PHAR "/github/workspace/bin/phplint.phar"

Publish:
> Error: EACCES: permission denied, open '/home/runner/work/phplint/phplint/bin/phplint.phar'

**Comment by llaville** [comment]
@overtrue I'll replace current https://github.com/overtrue/phplint/blob/9.0.2/.github/workflows/build-phar.yml workflow, by the new one https://github.com/overtrue/phplint/blob/main/.github/workflows/release.yml

PS: I've replaced my docker image that produce PHAR artifact in root mode, by invocation of the box-manifest PHAR version

Advantage:  
- Automation to prepare (write) new release with CHANGELOG fragment corresponding to version. Gave something like 

![github com_overtrue_phplint_releases_tag_untagged](https://user-images.githubusercontent.com/364342/218777954-ac85d2cb-0181-464e-b2fe-5467048ddd29.png)

- We ca run it manually (see `workflow_dispatch`) 

![release-workflow](https://user-images.githubusercontent.com/364342/218778180-7c84600a-0d48-41f3-9b1d-4618856a0539.png)

**NOTE** The draft mode (checkbox on workflow dispatch dialog box) when enable allow a chance to preview/modify before publish it definitively !

**Comment by llaville** [comment]
FYI: I'll clean-up repository, due to all my tests in few minutes, and publish the new release 9.0.3

**Comment by llaville** [comment]
@overtrue FYI :
I've played a bit with new workflow, but PHAR distribution is now available.
I'll close this report, but I need to improve the new https://github.com/overtrue/phplint/blob/9.0.3/.github/workflows/release.yml for next release
