### ISSUE TITLE
Bug not reflecting the right error message

### ISSUE THREAD

**Issue by ThomasRalee** [overtrue/phplint#18]
Hi, I did a scan and i see bugs error returning this

````
home/vagrant/Code/helixtap/app/Analytic.php: {
file: "/home/vagrant/Code/helixtap/app/Analytic.php",
error: "Usage: php-fpm7.0 [-n] [-e] [-h] [-i] [-m] [-v] [-t] [-p <prefix>] [-g <pid>] [-c <file>] [-d foo[=bar]] [-y <file>] [-D] [-F [-O]]",
line: 0
},
````

Am i missing something?

**Comment by overtrue** [comment]
Please provide a detailed context.

**Comment by ThomasRalee** [comment]
Hi,

I am running Laravel 5.4, PHP7. 
I installed overture/phplint on my application folder directory and ran this script 
````
        $path =  realpath(__DIR__ . '/../..');
        $exclude = ['vendor'];
        $extensions = ['php'];

        $linter = new Linter($path, $exclude, $extensions);
        $errors = $linter->lint();

        return $errors;
````

Its returning the errors as intended. But the error message are not really helpful. 

'<img src="https://s29.postimg.org/adgko0vhj/Screen_Shot_2017-03-24_at_11.17.12_pm.png"></img>` 

I am suspecting that its because of php7? I cant be sure. Please advice.

**Comment by overtrue** [comment]
@ThomasRalee OK, I got it, I will fix it as soon as possible.

**Comment by ThomasRalee** [comment]
@overtrue Hi Sir, Any news on the fix?

**Comment by overtrue** [comment]
@ThomasRalee Fixed. 😄
