### ISSUE TITLE
Install via .phive/phars.xml

### ISSUE THREAD

**Issue by sitepark-veltrup** [overtrue/phplint#189]
# Install via .phive/phars.xml

## Summary
It is not possible to install phplint via `.phive/phars.xml`.
Currently phplint can only be installed via phive with the `--force-accept-unsigned` option.

## Description
Currently phplint can only be installed via phive with the `--force-accept-unsigned` option.
However, it is not possible to install phplint via a `.phive/phars.xml` like this one
```xml
<?xml version="1.0" encoding="UTF-8"?>
<phive xmlns="https://phar.io/phive">
   <phar name="phplint" version="^9.0" copy="false" />
</phive>
```
In the XML, `force-accept-unsigned` cannot be set.

A solution would be to make the `.asc` available again. See also #103

**Comment by sitepark-veltrup** [comment]
```sh
phive install overtrue/phplint --force-accept-unsigned
```

creates an entry in `.phive/phars.xml`

**Comment by llaville** [comment]
Also, take care about `phars.xml` contents and phar name.

When I put a  `<repo>/.phive/phars.xml` file as follow : 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<phive xmlns="https://phar.io/phive">
    <phar name="overtrue/phplint" version="^9.0" copy="false" />
</phive>
```

And run `phive install --force-accept-unsigned`, it will works !

**Comment by llaville** [comment]
@sitepark-veltrup BTW, thanks for reporting, it allowed to clarify/enhance documentation.
