### ISSUE TITLE
Use non-absolute paths in cache

### ISSUE THREAD

**Issue by crabmusket** [overtrue/phplint#198]
# New Feature

## Problem

I run phplint in CI, and would like to cache across runs. However, the cache [uses absolute file paths](https://github.com/overtrue/phplint/blob/fcd227df5fe62e87a22ef08e0fcbc927313a15f6/src/Linter.php#L106-L108), which may be different on each run.

## Suggested solution

I propose adding an option to provide a "source base path", and all file paths will be treated as relative to the base path when being added to the cache.

I'm happy to implement this feature!

**Comment by llaville** [comment]
Alternative to change current behavior (absolute/relative path in cache system) is to use dependency-injection system by providing an instance of the Cache : see https://github.com/overtrue/phplint/blob/9.0/src/Linter.php#L68

In this case, you may be able to change the current cache system without to change the core of the linter

**Comment by llaville** [comment]
@crabmusket You don't reply yet to @overtrue since a week.
As the next version 9.1.0 is almost ready for an official release, I would like to know if we should or not work on an alternative solution ?

**Comment by crabmusket** [comment]
Sorry for the very slow reply! I did some more investigating and realised that actually in our CI builds the filepath remains consistent - it's possible I was seeing cache misses for other reasons. I'll close this for now and maybe come back to it if it continues to be a problem.

> use dependency-injection system by providing an instance of the Cache

This is a great tip, thanks!
