### ISSUE TITLE
PHP7 parsing error 

### ISSUE THREAD

**Issue by generalconsensus** [overtrue/phplint#20]
When you are testing a php 7 on a php 5.6.3 system, of course there will be blood. I found this out with the spaceship operator. 

```
      return $item2['title'] <=> $item1['title'];
```

This causes a parse error which stops phplint. Probably not a bug since it's user error to test a php7 codebase with an older version of php, but still wanted to pass this along just the same. Thanks!

**Comment by overtrue** [comment]
so, I will make a database to support all of the PHP features?

**Comment by rmrhz** [comment]
@generalconsensus Why on earth would you test 7 code on 5.6.3? If possible why not do it yourself?
