### ISSUE TITLE
"Inappropriate ioctl for device" when used as composer script

### ISSUE THREAD

**Issue by MHarutunian** [overtrue/phplint#27]
Hi,
first of all thank you for this great tool! Simple yet effective, just does what it's supposed to!

I noticed a small issue when being used as a script in composer.json. Running the phplint from the `/vendor/bin` directory directly works as expected:

```
phplint 0.2.4 by overtrue and contributors.

Loaded config from "/~/.phplint.yml"

Using cache.
E

Time: < 1 sec, Memory: 2.0 MiBMB

FAILURES!
Files: 6, Failures: 1

There was 1 errors:
1. /~/tests/Unit/Controller/ControllerTest.php:18
 unexpected '$service' (T_VARIABLE) in line 18
```
However, running it as a composer script (e.g. `composer lint:syntax`) will display stty warnings:
```
> ./vendor/bin/phplint
phplint 0.2.4 by overtrue and contributors.

Loaded config from "/~/.phplint.yml"

Using cache.
stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device
E

Time: < 1 sec, Memory: 2.0 MiBMB

FAILURES!
Files: 6, Failures: 1

There was 1 errors:
1. /~/tests/Unit/Controller/ControllerTest.php:18
 unexpected '$service' (T_VARIABLE) in line 18
Script ./vendor/bin/phplint handling the lint:syntax event returned with error code 1
```
The script is defined in composer.json as follows:
```
"lint:syntax": "./vendor/bin/phplint"
```
I am using phplint 0.2.4 with PHP 7.2 and composer 1.5.6 on Ubuntu 17.10.

It is noteworthy that colors are working when running phplint directly (`./vendor/bin/phplint`) but not when being run from composer (`composer lint:syntax`). I guess that the stty error messages are related to the coloring of the phplint output.

Also note that I am successfully using composer scripts for other similar tools like phpcs, phpmd and phpunit, and no such error messages appear in any of these. Colors in phpunit are also working when being run through composer scripts.

If you need any additional information or I can do anything to resolve this issue, let me know.

Thanks!

**Comment by overtrue** [comment]
Thanks for feedback! Let me check the problem.

**Comment by overtrue** [comment]
Please try to use the `dev-master` branch, and update the composer script to:

```json
"scripts": {
    "lint:syntax": "./vendor/bin/phplint --ansi"
  }
```

**Comment by MHarutunian** [comment]
That was fast, thanks for the quick fix. Unfortunately I couldn't install `phplint` from the master branch, cause apparently Symfony 4 is no longer allowed (which I was using in my project):

Before composer.json was like this (from https://github.com/overtrue/phplint/commit/1cf777592f3b1ded0b633638decee8ae26034d29):
```
"symfony/console": "^2.7 || ^3.0 || ^4.0",
"symfony/finder": "^2.7 || ^3.0 || ^4.0",
"symfony/process": "^2.7 || ^3.0 || ^4.0",
"symfony/yaml": "^2.7 || ^3.0 || ^4.0"
```
now it looks like this (from https://github.com/overtrue/phplint/commit/fea53e72cd84bc678ba174fa521c927a65e95aa2):
```
"symfony/console": "^3.0",
"symfony/finder": "^3.0",
"symfony/process": "^3.0",
"symfony/yaml": "^3.0"
```

To briefly test this, I created a new, empty project with a single file with syntax errors. `phplint` was working in 1.0.0 when used from the CLI, but as a composer script it was showing the error. I then installed the `phplint` master branch with your recent changes, and now it's throwing Fatal Errors (TypeErrors) and I can't use it at all:
```
./vendor/bin/phplint index.php 
phplint 1.0.1 by overtrue and contributors.

No config file loaded.

PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Overtrue\PHPLint\Command\LintCommand::Overtrue\PHPLint\Command\{closure}() must be an instance of Symfony\Component\Finder\SplFileInfo, instance of SplFileInfo given, called in /~/vendor/overtrue/phplint/src/Linter.php on line 118 and defined in /~/vendor/overtrue/phplint/src/Command/LintCommand.php:216
Stack trace:
#0 /~/vendor/overtrue/phplint/src/Linter.php(118): Overtrue\PHPLint\Command\LintCommand->Overtrue\PHPLint\Command\{closure}('error', Object(SplFileInfo))
#1 /~/vendor/overtrue/phplint/src/Command/LintCommand.php(235): Overtrue\PHPLint\Linter->lint(Array, true)
#2 /~/vendor/overtrue/phplint/src/Command/LintCommand.php(175): Overtrue\PHPLint\Command\LintCommand->executeLint(Object(Overtrue\PHPLint\Linter), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\Consol in /~/vendor/overtrue/phplint/src/Command/LintCommand.php on line 216
```
This happens in both `./vendor/bin` and when called as a composer script.

I then realized I hadn't defined a config file yet (it should work anyways, right?), so I added a `.phplint.yml` in my otherwise empty project, and the error disappeared. Note that it was working without the config file in 1.0.0 (maybe because of the Symfony 4 dependency?), but not in 1.0.1.

**Comment by overtrue** [comment]
let me fix it.

**Comment by overtrue** [comment]
@MHarutunian Plz try again.

**Comment by MHarutunian** [comment]
Great, everything works now - Symfony 4 install, TypeError and the original stty error have been fixed. Thanks a lot for the quick help!

**Comment by overtrue** [comment]
@MHarutunian Thanks for your feedback. 😆

**Comment by overtrue** [comment]
@MHarutunian Try to add option `-v` and you will see a more detailed output.
