### ISSUE TITLE
Available as a PHAR?

### ISSUE THREAD

**Issue by jdrydn** [overtrue/phplint#29]
Is this available as a standalone PHAR? If not could it be, under **Releases** I can see source code downloads but if a standalone package was to be distributed that would be a good place to store it under?

**Comment by overtrue** [comment]
I am working on it.

**Comment by eclipxe13** [comment]
Nice, would you consider also sign the phar file to include it into phive tool ?
https://phar.io/howto/sign-and-upload-to-github.html

**Comment by overtrue** [comment]
@eclipxe13 @jdrydn After considering, more and more similar tools are recommended to use the Composer way to install, so I do not intend to package it.

**Comment by spelcaster** [comment]
https://twitter.com/s_bergmann/status/999635212723212288

**Comment by c33s** [comment]
as it is a ci tool it should not interfere with project dependencies. phar would be the prefered way for ci tools to install. see phpstan, php-cs-fixer, composer-unused, composer-require-checker, phpunit, ... 
so i wouldn't say that composer is the "recommended" way.
just me 2ct

**Comment by jdrydn** [comment]
Wow, this thread is a throwback! 😂 From the looks of it, @overtrue has added Docker support & GitHub Actions, but still no PHAR, so I guess the reason is entirely developer preference 🤷‍♂️ 

@c33s Looks like you could install Docker to your platform & run it directly on your codebase, with something like (untested):
```sh
$ docker run --rm -it -w /workspace -v $PWD:/workspace overtrue/phplint:latest ./ --exclude=vendor
```

@overtrue There's (now) GitHub Actions for creating/uploading releases, and looks like you'd just need to write a PHP script to compile this package into [create a PHAR](https://blog.programster.org/creating-phar-files) 👍

**Comment by overtrue** [comment]
https://github.com/overtrue/phplint/releases/tag/2.3.5

**Comment by overtrue** [comment]
Hi, all. All future new releases will be accompanied by a Phar package. :smile:
