### ISSUE TITLE
Only lint files changed compared to master

### ISSUE THREAD

**Issue by rlweb** [overtrue/phplint#33]
For local developement on a large code base, sometimes running code lint across the whole codebase in unnecessary but running across a diff of files changes compared to say master.

This may be a useful feature, I may come back and create a PR soon.

**Comment by rmrhz** [comment]
I also agree on this.

**Comment by overtrue** [comment]
👍

**Comment by funivan** [comment]
We solved this issue with the following command in our CI configuration:
```
git diff --name-only HEAD~ HEAD | xargs ./vendor/overtrue/phplint/bin/phplint -v --no-cache --configuration=./.phplint.yml
```

**Comment by overtrue** [comment]
@funivan 👍

**Comment by exussum12** [comment]
That is only for one commit

I would suggest `git diff --name-only origin/master...`  for commits relative to master made only on this branch

**Comment by overtrue** [comment]
Since everyone's environment is different, the definition of "changed files" is not the same, so this is not intended to be built in here.

You can use the command to filter out the files you want to check and invoke the command check just like the above.

Thanks @rlweb @exussum12 @funivan @rmrhz
