### ISSUE TITLE
What does the cache do?

### ISSUE THREAD

**Issue by willemstuursma** [overtrue/phplint#34]
Why is this a faster library, e.g. compared to https://github.com/JakubOnderka/PHP-Parallel-Lint?

What does the cache do, what is it used for?

**Comment by overtrue** [comment]
sorry. I did not know the existence of **PHP-Parallel-Lint** before, this is a self-use library, and then put it to GitHub, the cache is used to speed up the inspection, only check for changed files.

Thank you.

**Comment by eclipxe13** [comment]
I've migrated from parallel-lint to phplint.
* Pros: is faster and cache make it really fast for big projects
* Cons: Less options like:
  - git blame
  - showing the portion of the source code with error
  - output in json format
  - files from stdin

None of these options I use, decision was easy.

**Comment by overtrue** [comment]
@eclipxe13 😄

**Comment by eclipxe13** [comment]
:smile: now it contains "showing the portion of the source code with error" and "output in json format", still didn't notice any performance issue (just my perception)
