### ISSUE TITLE
Undefined variable

### ISSUE THREAD

**Issue by mimmi20** [overtrue/phplint#35]
PHP Notice:  Undefined index: cache in /home/developer/projects/BrowserDetector/vendor/overtrue/phplint/src/Command/LintCommand.php on line 157
PHP Stack trace:
PHP   1. {main}() /home/developer/projects/BrowserDetector/vendor/overtrue/phplint/bin/phplint:0
PHP   2. Overtrue\PHPLint\Console\Application->run() /home/developer/projects/BrowserDetector/vendor/overtrue/phplint/bin/phplint:32
PHP   3. Overtrue\PHPLint\Console\Application->doRun() /home/developer/projects/BrowserDetector/vendor/symfony/console/Application.php:143
PHP   4. Overtrue\PHPLint\Console\Application->doRunCommand() /home/developer/projects/BrowserDetector/vendor/symfony/console/Application.php:241
PHP   5. Overtrue\PHPLint\Command\LintCommand->run() /home/developer/projects/BrowserDetector/vendor/symfony/console/Application.php:865
PHP   6. Overtrue\PHPLint\Command\LintCommand->execute() /home/developer/projects/BrowserDetector/vendor/symfony/console/Command/Command.php:252

**Comment by overtrue** [comment]
What's your PHP version ?

**Comment by overtrue** [comment]
And what's the version of overtrue/phplint?

**Comment by mimmi20** [comment]
PHP: 7.1.13
phplint: 1.0.3

**Comment by overtrue** [comment]
https://github.com/overtrue/phplint/blob/master/src/Command/LintCommand.php#L157

https://3v4l.org/qUWfe

**Comment by mimmi20** [comment]
This was fixed after the release of the version 1.0.3.

**Comment by overtrue** [comment]
@mimmi20 OK, sorry, I make a release 1.0.4 😆
