### ISSUE TITLE
cache store whould only be called once

### ISSUE THREAD

**Issue by eclipxe13** [overtrue/phplint#41]
I think the line where cache is stored [`$cache && Cache::put($newCache);`](https://github.com/overtrue/phplint/blob/24434a966abe2054bd2e1978cce5a704e6ae729d/src/Linter.php#L126) shoud be outside the loop.

As it is inside the main loop (while there are still ending files or running processes) the action of persist the cache array is called several times.

The main loop in `Linter::lint` exits after all files has been linted, and it populates the arrays `$errors`, `$newCache`. Once the loop is over then the cache must be persisted.

Please consider move `$cache && Cache::put($newCache);` outside the main loop.

**Comment by overtrue** [comment]
👍
