### ISSUE TITLE
你好，有 rule 列表吗？

### ISSUE THREAD

**Issue by jason-chang** [overtrue/phplint#43]
你好，有 rule 列表吗？

**Comment by overtrue** [comment]
啥 rule?

**Comment by jason-chang** [comment]
@overtrue  就是规则啊, 类似 eslint 的
https://eslint.org/docs/rules/

**Comment by overtrue** [comment]
它是 php 语法错误检查工具，不是代码规范检查工具，规则是 php 解释器定的

发自我的 iPhone

**Comment by jason-chang** [comment]
@overtrue 了解了，大神知道可用的 php 代码规范检查工具吗？

**Comment by overtrue** [comment]
- https://style-ci.io
- https://scrutinizer-ci.com/g/overtrue/wechat/?branch=master
- https://github.com/squizlabs/PHP_CodeSniffer
