### ISSUE TITLE
Exit with 0 on empty files

### ISSUE THREAD

**Issue by estahn** [overtrue/phplint#47]
We're running phplint like this:

```
git whatchanged --name-only --pretty="" origin..HEAD | sort | uniq | xargs ~/.composer/vendor/bin/phplint
```

Would it be possible to return 0 if no files are linted?

**Comment by estahn** [comment]
@overtrue This is a non-issue now. I'm scanning now all files (>10k) which takes approx 1min without cache. With cache is just a couple of seconds max.

**Comment by overtrue** [comment]
@estahn OK.
