### ISSUE TITLE
How to detect undefined parameters or variables

### ISSUE THREAD

**Issue by nwaughachukwuma** [overtrue/phplint#58]
Hi @overtrue, is this package able to capture errors for undefined/uninitialized variables? For example

```
// $user = Auth::user(); <-- commented this out so $user is not initialized in next lin
$user->notify(new NewTicketPurchase());
```

will the package discover that the $user in second line is not initialized?

**Comment by overtrue** [comment]
Maybe you need this https://github.com/phpstan/phpstan

**Comment by nwaughachukwuma** [comment]
Awesome @overtrue, thanks!
