### ISSUE TITLE
-j/--jobs parameter description or behaviour wrong

### ISSUE THREAD

**Issue by Gaibhne** [overtrue/phplint#60]
Using `/phplint src --no-cache --no-ansi --no-interaction -j=1` will hang the process (indefinitely, as far as I can tell, although I only gave it ~10 Minutes). Using `/phplint src --no-cache --no-ansi --no-interaction -j 1` instead (without the = in front of the number) appears to not only not hang, but actually take the 1 as a parameter - I end up with 11 seconds with `-j 1` and 3 seconds with `-j 4`. So I'd say either the help printout in the readme is wrong or the parsing code is wrong.

**Comment by overtrue** [comment]
@Gaibhne Hi, This command is based on symfony/console component: 

https://symfony.com/doc/current/console/input.html#using-command-options

> Note that to comply with the [docopt standard](http://docopt.org/), long options can specify their values after a white space or an = sign (e.g. --iterations 5 or --iterations=5), but short options can only use white spaces or no separation at all (e.g. -i 5 or -i5).

FYI.  [Docopt Standard](http://docopt.org/)

**Comment by Gaibhne** [comment]
Fair enough. I would still argue that crashing/hanging on an incorrect parameter is probably more on the bug side than the working as intended side.
