### ISSUE TITLE
`exclude` option seems to be relative only

### ISSUE THREAD

**Issue by jasonmccreary** [overtrue/phplint#65]
Given the I have the directory structure:

- src
- tests
  - fixtures

I wanted to `exclude` the `test/fixtures` folder, so I set the option `exclude=tests/fixtures`. However, these files were still included.

After some toying around, I passed `exclude=fixtures` and there were properly excluded.

However, given I was running the `phplint` from the project root, I would expect the former to work.

**Comment by overtrue** [comment]
@jasonmccreary Sorry for not replying to you until now, the `exclude` is relative to target path(default: `.`),  please show me the full command to me, I can't reduce the problem. Thanks.

**Comment by jasonmccreary** [comment]
I see. Makes sense I suppose. Thanks.
