### ISSUE TITLE
composer require overtrue/phplint失败

### ISSUE THREAD

**Issue by v-leonhou** [overtrue/phplint#7]
我执行composer require overtrue/phplint好长时间，终端一直卡在加载界面，尝试是composer.json权限问题，于是修改权限777，还是不行，最后还是手动修改composer.json解决的

**Comment by overtrue** [comment]
@v-leonhou 网络问题吧

**Comment by wangyaoxu** [comment]
这样的 ![git](http://ww1.sinaimg.cn/mw690/710e403bjw1f69o46l9pqj21320c0wnb.jpg)

**Comment by overtrue** [comment]
@wangyaoxu 你的项目依赖了 symfony/console 2.7.15 与当前这个工具所依赖的冲突了，冲突的情况下建议你全局装，这样就不会冲突，所有项目都可以使用：

```shell
$ composer global require overtrue/phplint -vvv
```
使用：

```shell
$ phplint --help
```

当然，你肯定得把你的 composer bin 目录加到 PATH 中：`~/.composer/vendor/bin` 才能作为全局命令使用。

**Comment by wangyaoxu** [comment]
@overtrue 感谢超哥回复。是在新建的项目里运行的，开发环境是homestead，运行 composer global require overtrue/phplint -vvv 依然报同样的错误

**Comment by overtrue** [comment]
@wangyaoxu 全局安装也冲突？

**Comment by wangyaoxu** [comment]
@overtrue  是的额

**Comment by overtrue** [comment]
@wangyaoxu 那我还是建议你更新你的依赖吧，2.7 已经很旧了

**Comment by wangyaoxu** [comment]
@overtrue 试了一下 laravel 5.2 然后安装成功了

**Comment by overtrue** [comment]
嗯

On 周五, 7月 29, 2016 at 3:59 下午, Sugar <notifications@github.com> wrote:
@overtrue [https://github.com/overtrue] 试了一下 laravel 5.2 然后安装成功了
