### ISSUE TITLE
Path from config file not used

### ISSUE THREAD

**Issue by peterkoppenaal** [overtrue/phplint#73]
Hi, 

after upgrading to 2.0.0 the path variable in my .phplint.yml stopped working. 
Contents of my yml file: 
```
path: ./app/
jobs: 10
cache: var/tmp/phplint.cache
extensions:
  - php
```

When I add the path variable to the CLI command, it works.
Could this be caused by this commit? 
https://github.com/overtrue/phplint/commit/0e94daed43fe7a929bf892cb2290cb9af3ed4597

best regards
Peter

**Comment by overtrue** [comment]
I am sorry, It's fixed.
