### ISSUE TITLE
Version identifier for 2.0.0 release marked as 1.2.5 in package

### ISSUE THREAD

**Issue by pramser** [overtrue/phplint#75]
My `composer.json` is pulling version 2.0 for the current phplint package:

```
"overtrue/phplint": "^2.0",
```

In the library, the version is reflected as 1.2.5:

```
/var/www $ vendor/bin/phplint --version
phplint 1.2.5
```

Should be a simple bug/fix. Wanted to point it out so future issues and documentation can be properly reported.

**Comment by overtrue** [comment]
Please update to 2.0.2 :

```sh
$ composer update overtrue/phplint
```
