### ISSUE TITLE
PHP 7.4 array functions support

### ISSUE THREAD

**Issue by vbezruchkin** [overtrue/phplint#78]
Hi,

Thanks for the package. I wonder if you have any plans to support PHP closures. I have a CI configured with your docker, and it generates errors like:

```
5. /builds/XXX/app/Providers/NovaServiceProvider.php:24
    21|     {
    22|         parent::boot();
    23| 
  > 24|         Nova::createUserUsing(fn($command) => [
    25|             $command->ask('Username'),
    26|             $command->ask('Email Address'),
    27|             $command->secret('Password'),
 unexpected '=>' (T_DOUBLE_ARROW), expecting ')' in line 24
```

Thanks

**Comment by overtrue** [comment]
Hi, arrow functions can only have one expression, which is the return statement. 

FYI: https://stitcher.io/blog/short-closures-in-php

**Comment by overtrue** [comment]
So, you must use `function(){}` if you have multi-line expressions.

**Comment by vbezruchkin** [comment]
Thanks for the confirmation. Yes, seems quite reasonable.

Cheers

**Comment by overtrue** [comment]
@vbezruchkin 🍻
