### ISSUE TITLE
-q 指令的使用场景和检测结果的一次性输出需求

### ISSUE THREAD

**Issue by IvanChou** [overtrue/phplint#8]
你好，
我在将这个工具集成到 capistrano 自动化部署的过程中，发现一个小小的问题

phplint 在输出检测结果的时候是动态输出的，这会导致 pty 将其认为是多次输出，从而将中间过程不停的输出到屏幕上

![2016-08-15 2 53 27](https://cloud.githubusercontent.com/assets/2182089/17657707/0f646d22-62f8-11e6-81b4-b76277f8bac3.png)

使用 -q 参数后，所有的输出都没有了(包括报错)，phplint 也没有输出到日志的设置，有点不理解 -q 的使用场景

PS: 是否考虑对 laravel 再多一点兼容，允许使用 `php artisan phplint` 来调用命令

**Comment by overtrue** [comment]
1. 这个组件是基于  [symfony/console] 开发的，所以 `-q` 选项是框架带的
2. 关于这个动态输出的问题，我再看看这个框架是否有提供选项
3. 首先它是检查 PHP 代码语法错误的，所以它应该就是最顶层的角色，如果把它放到代码里的话，那你的框架代码出问题的时候它自身都跑不起来了，哈哈

**Comment by IvanChou** [comment]
我试着加了一个 `brief-output` 的参数解决了这个问题
需要提 PR 么

**Comment by overtrue** [comment]
@IvanChou 提 ❤️

**Comment by overtrue** [comment]
@IvanChou 试试 0.0.3

**Comment by IvanChou** [comment]
![2016-08-15 10 48 55](https://cloud.githubusercontent.com/assets/2182089/17668134/853cd1aa-633a-11e6-9e5e-edb9c4de7fec.png)

capistrano 的终端日志返回貌似不能在某一行上面追加或修改，只能另外输出一行，于是就成了这样
这个样子已经是可以接受了

看了下  symfony/console  的 output，里面有一个输出信息分级的设定，我明天再试着去尝试一下

PS: 想想，其实这个需求好小众 😅

**Comment by overtrue** [comment]
@IvanChou 哈哈，我尝试了在 Travis-CI 里看是正常的，所以我怀疑应该是你这个工具它会实时抓取变化。。。

**Comment by IvanChou** [comment]
我想了一下，这个需求太小众，如果只是为了去解决它而向项目中插入不必要的代码好像有点得不偿失

既然是在项目的自动化部署过程中遇到的问题，放到项目自身中去解决应该也是合适的。
所以最后我还是决定通过一个 laravel console 来解决这个问题

十分感谢您的支持 😆
