### ISSUE TITLE
Problem with lint in PHP7.4

### ISSUE THREAD

**Issue by AnLuizMM** [overtrue/phplint#86]
When I run lint using PHP7.4 the problem occurred to recognize the typing in the variables.
![image](https://user-images.githubusercontent.com/32845476/95488724-442f4a80-096c-11eb-9a97-54ae1a0281ee.png)
![image](https://user-images.githubusercontent.com/32845476/95488890-793b9d00-096c-11eb-808d-45420449b991.png)

Is there some setting to solve this?

**Comment by overtrue** [comment]
Plz check your php cli version:

```bash
$ php -v 
```

**Comment by AnLuizMM** [comment]
> Plz check your php cli version:
> 
> ```shell
> $ php -v 
> ```

I'm using lint on Github Action and this is the PHP configuration during execution
![image](https://user-images.githubusercontent.com/32845476/95571138-5659c900-09fe-11eb-93c1-3acff46e2646.png)

does it help?

**Comment by overtrue** [comment]
It does seem to be a problem with the PHP version, maybe you need to double-check the environment, I don't have a better idea right now.

**Comment by NorthenIrbis** [comment]
@overtrue Can you update the version of PHP in your Dockerfile? https://github.com/overtrue/phplint/blob/master/Dockerfile

**Comment by overtrue** [comment]
@NorthenIrbis done.

**Comment by NorthenIrbis** [comment]
@overtrue Thanks!!!
