### ISSUE TITLE
I ran against a magento repo

### ISSUE THREAD

**Issue by shuat** [overtrue/phplint#92]
I ran the following 

./vendor/bin/phplint ./app/code -j 10 -w

Is this linter suppose to catch an undefined variable?
I use vscode and it warns that my variable is undefined using intelephsense.
Is this linter suppose to pick that up?

**Comment by overtrue** [comment]
This package is a wrapper of the command `php -l`, it cannot found the undefined variable error, may be you need this: https://github.com/phpstan/phpstan
