### ISSUE TITLE
Compatibility with PHP 8

### ISSUE THREAD

**Issue by jasonmccreary** [overtrue/phplint#94]
While this package appears to be compatible with PHP 8 from a dependency perspective, it does not seem to work within my GitHub Actions.

It's failing with a syntax error for the new `match` statement.

```txt
    33|         $suffix = match ($this->code) {
  > 34|             3 => 'composer',
    35|             11 => 'branch',
    36|             default => 'generic',
    37|         };
 unexpected '=>' (T_DOUBLE_ARROW) in line 34
```

This may simply be a configuration issue, but my job is running PHP 8.0 via the [shivammathur/setup-php@v2](https://github.com/shivammathur/setup-php) step. Any guidance for ensuring this step uses PHP 8 would be appreciated. Thanks.

**Comment by overtrue** [comment]
`php -v`

**Comment by jasonmccreary** [comment]
```
Run php -v
PHP 8.0.5 (cli) (built: May  3 2021 11:30:57) ( NTS )
```

This was added prior to the step `Run overtrue/phplint@master`. My guess is this step is not using the PHP version of the job, but it's own (7.4).

**Comment by overtrue** [comment]
I will fix this later.

发自我的iPhone

**Comment by overtrue** [comment]
@jasonmccreary plz try to use `uses: overtrue/phplint@8.0`

**Comment by jasonmccreary** [comment]
That did it. I assume I should use this tag to get the PHP 8.0 build of phplint?

**Comment by overtrue** [comment]
Yes

发自我的iPhone

**Comment by overtrue** [comment]
@jasonmccreary Sorry, my reply above is wrong, it should be using 3.0, docker  tag is 8.0.
