### ISSUE TITLE
Syntax Error in 7.4

### ISSUE THREAD

**Issue by quickbutik-ronflorax** [overtrue/phplint#95]
There seems to be a syntax error on the 7.4-branch:

`PHP Parse error:  syntax error, unexpected '|', expecting variable (T_VARIABLE) in /root/.composer/vendor/overtrue/phplint/src/Linter.php on line 21`

**Comment by overtrue** [comment]
composer installed ? or github action?

**Comment by overtrue** [comment]
Fixed.

**Comment by michield** [comment]
So, the linter project doesn't lint it's own code? :-)

If it's fixed, can you publish it? It's not working on my CI yet

https://github.com/phpList/phplist3/actions/runs/909520804

**Comment by overtrue** [comment]
@michield Sorry, this is a legacy issue, I fixed [an issue in 2.4.0](https://github.com/overtrue/phplint/commit/decfac40d5349055553360d3f626a0e39419351d) where the previous version of composer require did not specify a version, causing the latest version to be installed during action installation, resulting in 3.x being installed. We recommend updating your dependencies to 2.4 or higher, sorry for the inconvenience.

**Comment by overtrue** [comment]
https://github.com/phpList/phplist3/runs/2753428957?check_suite_focus=true#step:2:82

**Comment by michield** [comment]
ok, thanks
